-- AlterEnum
ALTER TYPE "TipoCampoServicio" ADD VALUE 'PLACA_VEHICULO';
ALTER TYPE "TipoCampoServicio" ADD VALUE 'LICENCIA_CONDUCIR';
ALTER TYPE "TipoCampoServicio" ADD VALUE 'FOTO';
ALTER TYPE "TipoCampoServicio" ADD VALUE 'PRODUCTO_CATALOGO';
